server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30


spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: localhost
    prot: 6739
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    username: root
    password: root



#management:
  #security:
   # enabled: true
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 18000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.example.**.entity
  global-config:
    refresh: true
    banner: false
    db-config:
      id-type: UUID
  configuration:
    call-setters-on-nulls: true







